name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files to public directory
        run: |
          mkdir -p public
          cp -r src/* public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          publish_dir: ./public
          publish_branch: gh-pages
